config/routes.rb
Rails.application.routes.draw do
  resources :vinyls
  devise_for :users, :path_prefix => 'my'
  resources :users

  root to: "home#page"

  get 'listing/page', to: "listing#page"

  get "/contact", to: "contact#contact", as: "contact"


  get "/users/sign_up", to: "devise/registrations#new"
  delete "/users/:id", to: "users#destroy"

  post "/vinyls/:id/buy", to: "vinyls#buy", as: "buy"
  get "vinyls/:id/success", to: "vinyls#success", as: "success"
  get "vinyls/:id/cancel", to: "vinyls#cancel", as: "cancel"

  match '/500', to: "errors#internal_server_error", via: :all
  match '/404', to: "errors#not_found", via: :all
  get '*path', to: "errors#not_found"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
      
    user ||= User.new
      if user.has_role?(:admin)
        can :manage, :all
        can :manage, :user
      else
        can :manage, Vinyl, user_id: user.id
        can :read, :all
        can :buy, :all
        can :success, :all
        can :cancel, :all
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }, uniqueness: true

  validates_presence_of :username

  has_many :vinyls

  def assign_admin_default
    user = User.find_by_id(1)
    user.add_role(:admin)
  end

  def assign_default_role
    self.add_role(:collector)
  end
end

app/models/vinyl.rb
class Vinyl < ApplicationRecord
    attribute :price, default: 1.0

    validates :price, :length => { :maximum => 6 }

    validates_presence_of :title, :artist, :label, :genre, :year, :quality, :price

    has_one_attached :image

    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
     

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
          end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def contact
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 505
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/listing_controller.rb
class ListingController < ApplicationController
  def page
    @vinyls = Vinyl.where(availability: true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
     
    def destroy
        if current_user.has_role?(:admin)
        User.find(params[:id]).destroy
        redirect_to root_path
        else
        flash[:alert] = "That don't work! I see you!"
        redirect_to root_path
        end
    end
end

app/controllers/vinyls_controller.rb
class VinylsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:buy]
  load_and_authorize_resource
  before_action :check_roles
  before_action :set_vinyl, only: [:show, :edit, :update, :destroy, :buy]


  # GET /vinyls
  # GET /vinyls.json
  def index
    if current_user.has_role?(:admin)
    @vinyls = Vinyl.all
    else
    @vinyls = current_user.vinyls.all
    end
  end

  # GET /vinyls/1
  # GET /vinyls/1.json
  def show
  end

  # GET /vinyls/new
  def new
    @vinyl = current_user.vinyls.build
  end

  # GET /vinyls/1/edit
  def edit
  end

  # POST /vinyls
  # POST /vinyls.json
  def create
    @vinyl = current_user.vinyls.build(vinyl_params)
  

    respond_to do |format|
      if @vinyl.save
        format.html { redirect_to @vinyl, notice: 'Vinyl was successfully created.' }
        format.json { render :show, status: :created, location: @vinyl }
      else
        format.html { render :new }
        format.json { render json: @vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinyls/1
  # PATCH/PUT /vinyls/1.json
  def update
    authorize! :update, @vinyl
    respond_to do |format|
      if @vinyl.update(vinyl_params)
        format.html { redirect_to @vinyl, notice: 'Vinyl was successfully updated.' }
        format.json { render :show, status: :ok, location: @vinyl }
      else
        format.html { render :edit }
        format.json { render json: @vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinyls/1
  # DELETE /vinyls/1.json
  def destroy
    authorize! :destroy, @vinyl
    @vinyl.destroy
    respond_to do |format|
      format.html { redirect_to vinyls_url, notice: 'Vinyl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # put in paths later
  def buy
    Stripe.api_key = ENV['STRIPE_API_KEY']
    session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      mode: 'payment',
      success_url: success_url(params[:id]),
      cancel_url: cancel_url(params[:id]),
      line_items: [
        {
          price_data: {
            currency: 'aud',
            product_data: {
              name: @vinyl.title
            },
            unit_amount: (@vinyl.price * 100).to_i
          },
          quantity: 1
        }
      ]
    })

    render json: session
  end


  def success
    @vinyl.availability = false
    @vinyl.save!
    flash[:alert] = "Payment was successful! Go you!"
    redirect_to root_path
  end

  def cancel
    flash[:alert] = "The transaction was cancelled!"
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vinyl
      @vinyl = Vinyl.find(params[:id])
    end

    def check_roles
    end

    # Only allow a list of trusted parameters through.
    def vinyl_params
      params.require(:vinyl).permit(:title, :artist, :label, :genre, :year, :quality, :price, :description, :availability, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vinyls_helper.rb
module VinylsHelper
end

app/views/contact/contact.html.erb
<form action="https://formspree.io/f/myybpdkj" method="POST">
    <div class="form-group">
        <label for="exampleFormControlInput1">Your Name</label>
        <input type="text" name="Name" class="form-control" id="exampleFormControlInput1" placeholder="e.g. Anakin Skywalker">
      </div>
      <div class="form-group">
        <label for="exampleFormControlInput1">Email Address</label>
        <input type="email" name="Reply To" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Your Enquiry</label>
        <textarea class="form-control" name="message" id="exampleFormControlTextarea1" rows="5"></textarea>
      </div>
      <button type="submit">Send</button>
  </form>

app/views/home/page.html.erb
<div class="row">
<div class="jumbotron">
  <h1 class="display-4">Vinyl Destination</h1>
  <hr class="my-4">
  <p class="lead">
      <div class="col-md-6">
          <%= image_tag "vinyl-svg.png", class: "home-image" %>
      </div>
      <p>Welcome, <%= current_user.username%>!</p>
      <%= link_to "Go Browsing", listing_page_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Create Listing", new_vinyl_path, class: "btn btn-primary btn-lg" %>
    <% if current_user.has_role?(:admin) %>
    <%= link_to "All Records", vinyls_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "All Users", users_path, class: "btn btn-primary btn-lg" %>
    <% else %>
    <%= link_to "My Records", vinyls_path, class: "btn btn-primary btn-lg" %>
    <% end %>
    <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vinyl Destination</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>
    <div class="container">
    <%= render "partials/navbar" %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/listing/page.html.erb
<div class="search-field">
  <form class="form-inline my-2 my-lg-0">
    <%= link_to "Create Listing", new_vinyl_path, class: "tn btn-outline-success my-2 my-sm-0" %>
  </form>
</div>

<div class="row">
  <% @vinyls.each do |vinyl| %>
  <div class="col-md-4">
    <div class="card" style="width: 18rem">
      <%= cl_image_tag(vinyl.image.key, crop: :scale, width: 200, cloud_name: 'jbradz') if vinyl.image.attached? %>
      <div class="card-body">
        <h5 class="card-title"><%= vinyl.title %></h5>
        <p class="card-text"><%= vinyl.description %></p>
        <p class="card-text"><%= vinyl.price %></p>
        <%= link_to "Look", vinyl_path(vinyl.id), class:"btn btn-primary btn-right" %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<!--  image_tag vinyl.image(vinyl.key), class: "card-img-top" -->

app/views/partials/_error.html.erb
<p>Sorry, this page does not exist or you don't have permission.</p>
<%= link_to "Home page", root_path %>

app/views/partials/_ise.html.erb
<p>Sorry, this page does not exist or you don't have permission.</p>
<%= link_to "Home page", root_path %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Vinyl Destination</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= link_to "Browse", listing_page_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            <% end %>
          </li>
      </ul>
    </div>
  </nav>

app/views/users/index.html.erb
<table>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <% if current_user.has_role?(:admin) %>
        <td><%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure"} %></td>  
        <% end %> 
      </tr>
    <% end %>
    </tbody>
</table>

app/views/vinyls/_form.html.erb
<%= simple_form_for(@vinyl) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :artist %>
    <%= f.input :label %>
    <%= f.input :genre, collection: ["House", "Techno", "Disco", "Breaks", "Hip-Hop", "Rock", "Metal", "Jazz", "Alternative", "Funk/Soul", "Other"] %>
    <%= f.input :year, collection: 1950..2020 %>
    <%= f.input :quality, label: "Condition", collection: ["M", "NM", "VG+", "VG", "G+", "G", "F", "P"] %>
    <%= f.input :price, step: 0.01, min: 0.5, hint: "Prices are to be listed in AUD. Numbers only.", as: :decimal %>
    <%= f.input :description  %>
    <%= f.input :availability, label: "Tick if available now. If it's not, it won't be shown in the 'Browse' section." %>
    <%= f.file_field :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vinyls/edit.html.erb
<h1>Editing Vinyl</h1>

<%= render 'form', vinyl: @vinyl %>

<%= link_to 'Show', @vinyl %> |
<%= link_to 'Back', vinyls_path %>

app/views/vinyls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vinyls</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Label</th>
      <th>Genre</th>
      <th>Year</th>
      <th>Quality</th>
      <th>Price</th>
      <th>Description</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @vinyls.each do |vinyl| %>
      <tr>
        <td><%= vinyl.title %></td>
        <td><%= vinyl.artist %></td>
        <td><%= vinyl.label %></td>
        <td><%= vinyl.genre %></td>
        <td><%= vinyl.year %></td>
        <td><%= vinyl.quality %></td>
        <td><%= vinyl.price %></td>
        <td><%= vinyl.description %></td>
        <td><%= vinyl.availability %></td>
        <td><%= link_to 'Show', vinyl %></td>
        <td><%= link_to 'Edit', edit_vinyl_path(vinyl) %></td>
        <td><%= link_to 'Destroy', vinyl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Vinyl', new_vinyl_path %>

app/views/vinyls/new.html.erb
<h1>New Vinyl</h1>

<%= render 'form', vinyl: @vinyl %>

<%= link_to 'Back', vinyls_path %>

app/views/vinyls/show.html.erb
<p id="notice"><%= notice %></p>

<% if @vinyl.image.attached? %>
  <p>
    <%= cl_image_tag(@vinyl.image.key, crop: :scale, width: 200, cloud_name: 'jbradz') %>
  </p>
<% end %>


<p>
  <strong>Title:</strong>
  <%= @vinyl.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @vinyl.artist %>
</p>

<p>
  <strong>Label:</strong>
  <%= @vinyl.label %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @vinyl.genre %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vinyl.year %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @vinyl.quality %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vinyl.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vinyl.description %>
</p>

<p>
  <strong>Posted by:</strong>
  <%= @vinyl.user.username %>
</p>

<p>
  <button id="buynow-button">Buy Now!</button>
</p>

<script src="https://js.stripe.com/v3/"></script>

<script>
    const stripe = Stripe('<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>')
    const buyButton = document.getElementById('buynow-button')

    buyButton.addEventListener('click', function() {
      fetch('<%= buy_path(@vinyl.id) %>', {
        method: 'POST'
      })
      .then(function(response) {
        return response.json()
      })
      .then(function(session) {
        return stripe.redirectToCheckout({ sessionId: session.id })
      })
    })
</script>

<% if can? :update, @vinyl %>
<%= link_to 'Edit', edit_vinyl_path(@vinyl) %> |
<%= link_to 'Destroy', @vinyl, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', vinyls_path %>